# Generated by Django 3.1.4 on 2021-01-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aa',
            new_name='Wishlist',
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': 'Wishlists'},
        ),
    ]
