# Generated by Django 3.1.4 on 2021-01-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20210104_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='item_namesss',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
